name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - workflow

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.action == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Uninstall and reinstall Yarn globally
        run: sudo npm uninstall -g yarn && sudo npm install -g yarn
      - name: Install lint globally
        run: npm install -g lint
      - name: Lint project
        run: yarn lint
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Package code
        run: yarn package
      - name: Run tests
        run: yarn test
      - name: Publish release
        run: yarn release
